local opts = {
  ensure_installed = {
    "black",
    "clang-format",
    "clangd",
    "cmake-language-server",
    "codelldb",
    "cpptools",
    -- lspconfig.lua enables cssls; upstream never listed the server it needs
    "css-lsp",
    "cucumber-language-server",
    "cuelsp",
    "debugpy",
    "delve",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "emmet-ls",
    "go-debug-adapter",
    "gofumpt",
    "goimports",
    "goimports-reviser",
    "golangci-lint",
    "golangci-lint-langserver",
    "golines",
    "gomodifytags",
    "gopls",
    "gotests",
    "html-lsp",
    "iferr",
    "impl",
    "lua-language-server",
    "markdownlint",
    "mesonlsp",
    "mypy",
    "prettier",
    "prettierd",
    "protolint",
    "pyright",
    "ruff",
    "rust-analyzer",
    -- conform.lua formats lua with it, and .stylua.toml configures it
    "stylua",
    "svelte-language-server",
    "tailwindcss-language-server",
    "templ",
    "typescript-language-server",
  },
}

return {
  opts = opts,
}
